# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

polymul_mat <- function(amat, bmat) {
    .Call(`_sigex_polymul_mat`, amat, bmat)
}

VARMA_auto <- function(param, p, q, maxlag) {
    .Call(`_sigex_VARMA_auto`, param, p, q, maxlag)
}

getEigenValues <- function(M) {
    .Call(`_sigex_getEigenValues`, M)
}

complexExp <- function(x) {
    .Call(`_sigex_complexExp`, x)
}

polymult <- function(a, b) {
    .Call(`_sigex_polymult`, a, b)
}

polymul_mat <- function(amat, bmat) {
    .Call(`_sigex_polymul_mat`, amat, bmat)
}

ar_adjoint <- function(poly_array) {
    .Call(`_sigex_ar_adjoint`, poly_array)
}

auto_VARMA <- function(param, p, q, ps, qs, season, grid, maxlag) {
    .Call(`_sigex_auto_VARMA`, param, p, q, ps, qs, season, grid, maxlag)
}

getRe <- function(x) {
    .Call(`_sigex_getRe`, x)
}

getIm <- function(x) {
    .Call(`_sigex_getIm`, x)
}

getRagIndex <- function(zval) {
    .Call(`_sigex_getRagIndex`, zval)
}

subsetting <- function(x, y, z) {
    .Call(`_sigex_subsetting`, x, y, z)
}

matmult <- function(A, B) {
    .Call(`_sigex_matmult`, A, B)
}

kronprod <- function(A, B) {
    .Call(`_sigex_kronprod`, A, B)
}

vec2mat <- function(x) {
    .Call(`_sigex_vec2mat`, x)
}

mvar_midcast <- function(x_acf, z, delta, debug) {
    .Call(`_sigex_mvar_midcast`, x_acf, z, delta, debug)
}

